# Generated by Django 5.2.4 on 2025-09-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='dailyinventory',
            options={'verbose_name': 'موجودی روزانه', 'verbose_name_plural': 'موجودی\u200cهای روزانه'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='dailyinventory',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='dailyinventory',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventory', to='menu.menuitem', verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='dailyinventory',
            name='quantity_available',
            field=models.PositiveIntegerField(verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود است'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام غذا'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت'),
        ),
    ]
