# Generated by Django 5.2.4 on 2025-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options_alter_dailyinventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال است'),
        ),
    ]
