# Generated by Django 5.2.4 on 2025-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price_with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت با مالیات'),
        ),
    ]
