# Generated by Django 5.2.4 on 2025-10-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_price_with_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_without_tax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='قیمت بدون مالیات'),
            preserve_default=False,
        ),
    ]
