# Generated by Django 5.2.4 on 2025-10-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_vat_rate_alter_menuitem_price_with_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='vat_rate',
            field=models.IntegerField(choices=[(0, 'بدون مالیات (0%)'), (10, 'مالیات 10%'), (16, 'مالیات 16%')], default=10, help_text='درصد مالیات بر ارزش افزوده', verbose_name='نرخ مالیات بر ارزش افزوده'),
        ),
    ]
