# Generated by Django 5.2.4 on 2026-06-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='شماره میز')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام میز')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='ظرفیت')),
                ('status', models.CharField(choices=[('free', 'آزاد'), ('occupied', 'اشغال شده'), ('reserved', 'رزرو شده')], default='free', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میزها',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.table', verbose_name='میز'),
        ),
    ]
